// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/ticket.proto

package ticket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PurchaseTicketRequest - Request to purchase a ticket
type PurchaseTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseTicketRequest) Reset() {
	*x = PurchaseTicketRequest{}
	mi := &file_api_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseTicketRequest) ProtoMessage() {}

func (x *PurchaseTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseTicketRequest.ProtoReflect.Descriptor instead.
func (*PurchaseTicketRequest) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseTicketRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *PurchaseTicketRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *PurchaseTicketRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// PurchaseTicketResponse - Response containing the receipt
type PurchaseTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseTicketResponse) Reset() {
	*x = PurchaseTicketResponse{}
	mi := &file_api_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseTicketResponse) ProtoMessage() {}

func (x *PurchaseTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseTicketResponse.ProtoReflect.Descriptor instead.
func (*PurchaseTicketResponse) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseTicketResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// ViewUserReceiptRequest - Request to view user's receipt (empty, uses JWT)
type ViewUserReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewUserReceiptRequest) Reset() {
	*x = ViewUserReceiptRequest{}
	mi := &file_api_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewUserReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewUserReceiptRequest) ProtoMessage() {}

func (x *ViewUserReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewUserReceiptRequest.ProtoReflect.Descriptor instead.
func (*ViewUserReceiptRequest) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{2}
}

// ViewUserReceiptResponse - Response containing the user's receipt
type ViewUserReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewUserReceiptResponse) Reset() {
	*x = ViewUserReceiptResponse{}
	mi := &file_api_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewUserReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewUserReceiptResponse) ProtoMessage() {}

func (x *ViewUserReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewUserReceiptResponse.ProtoReflect.Descriptor instead.
func (*ViewUserReceiptResponse) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *ViewUserReceiptResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// ViewAllocationsRequest - Request to view all allocations
type ViewAllocationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by section (A or B). Empty means all sections
	Section       string `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewAllocationsRequest) Reset() {
	*x = ViewAllocationsRequest{}
	mi := &file_api_ticket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewAllocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewAllocationsRequest) ProtoMessage() {}

func (x *ViewAllocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewAllocationsRequest.ProtoReflect.Descriptor instead.
func (*ViewAllocationsRequest) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *ViewAllocationsRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

// ViewAllocationsResponse - Response containing all allocations
type ViewAllocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allocations   []*Allocation          `protobuf:"bytes,1,rep,name=allocations,proto3" json:"allocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewAllocationsResponse) Reset() {
	*x = ViewAllocationsResponse{}
	mi := &file_api_ticket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewAllocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewAllocationsResponse) ProtoMessage() {}

func (x *ViewAllocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewAllocationsResponse.ProtoReflect.Descriptor instead.
func (*ViewAllocationsResponse) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{5}
}

func (x *ViewAllocationsResponse) GetAllocations() []*Allocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

// Allocation - Represents a seat allocation
type Allocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	SeatNumber    int32                  `protobuf:"varint,2,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Allocation) Reset() {
	*x = Allocation{}
	mi := &file_api_ticket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Allocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Allocation) ProtoMessage() {}

func (x *Allocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Allocation.ProtoReflect.Descriptor instead.
func (*Allocation) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{6}
}

func (x *Allocation) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Allocation) GetSeatNumber() int32 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

func (x *Allocation) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// RemoveUserFromTrainRequest - Request to remove a user from the train
type RemoveUserFromTrainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: email of user to remove (for admin). If empty, removes the user from JWT
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromTrainRequest) Reset() {
	*x = RemoveUserFromTrainRequest{}
	mi := &file_api_ticket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromTrainRequest) ProtoMessage() {}

func (x *RemoveUserFromTrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromTrainRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromTrainRequest) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveUserFromTrainRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// RemoveUserFromTrainResponse - Response for removal operation
type RemoveUserFromTrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromTrainResponse) Reset() {
	*x = RemoveUserFromTrainResponse{}
	mi := &file_api_ticket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromTrainResponse) ProtoMessage() {}

func (x *RemoveUserFromTrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromTrainResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserFromTrainResponse) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveUserFromTrainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveUserFromTrainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ModifyUserSeatRequest - Request to modify a user's seat
type ModifyUserSeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: email of user to modify (for admin). If empty, modifies the user from JWT
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Section       string `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`                          // New section (A or B)
	SeatNumber    int32  `protobuf:"varint,3,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"` // New seat number (1-10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyUserSeatRequest) Reset() {
	*x = ModifyUserSeatRequest{}
	mi := &file_api_ticket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyUserSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserSeatRequest) ProtoMessage() {}

func (x *ModifyUserSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserSeatRequest.ProtoReflect.Descriptor instead.
func (*ModifyUserSeatRequest) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyUserSeatRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ModifyUserSeatRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *ModifyUserSeatRequest) GetSeatNumber() int32 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

// ModifyUserSeatResponse - Response containing updated receipt
type ModifyUserSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyUserSeatResponse) Reset() {
	*x = ModifyUserSeatResponse{}
	mi := &file_api_ticket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyUserSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserSeatResponse) ProtoMessage() {}

func (x *ModifyUserSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserSeatResponse.ProtoReflect.Descriptor instead.
func (*ModifyUserSeatResponse) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{10}
}

func (x *ModifyUserSeatResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// Receipt - Represents a ticket receipt
type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // "London"
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`     // "France"
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	PricePaid     int32                  `protobuf:"varint,4,opt,name=price_paid,json=pricePaid,proto3" json:"price_paid,omitempty"` // in cents, so $20 = 2000
	Seat          *Seat                  `protobuf:"bytes,5,opt,name=seat,proto3" json:"seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_api_ticket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{11}
}

func (x *Receipt) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Receipt) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Receipt) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Receipt) GetPricePaid() int32 {
	if x != nil {
		return x.PricePaid
	}
	return 0
}

func (x *Receipt) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

// User - Represents a user
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_ticket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{12}
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Seat - Represents a seat assignment
type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`                          // "A" or "B"
	SeatNumber    int32                  `protobuf:"varint,2,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"` // 1-10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_api_ticket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_api_ticket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_api_ticket_proto_rawDescGZIP(), []int{13}
}

func (x *Seat) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Seat) GetSeatNumber() int32 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

var File_api_ticket_proto protoreflect.FileDescriptor

const file_api_ticket_proto_rawDesc = "" +
	"\n" +
	"\x10api/ticket.proto\x12\x06ticket\"i\n" +
	"\x15PurchaseTicketRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"C\n" +
	"\x16PurchaseTicketResponse\x12)\n" +
	"\areceipt\x18\x01 \x01(\v2\x0f.ticket.ReceiptR\areceipt\"\x18\n" +
	"\x16ViewUserReceiptRequest\"D\n" +
	"\x17ViewUserReceiptResponse\x12)\n" +
	"\areceipt\x18\x01 \x01(\v2\x0f.ticket.ReceiptR\areceipt\"2\n" +
	"\x16ViewAllocationsRequest\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\"O\n" +
	"\x17ViewAllocationsResponse\x124\n" +
	"\vallocations\x18\x01 \x03(\v2\x12.ticket.AllocationR\vallocations\"i\n" +
	"\n" +
	"Allocation\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x12\x1f\n" +
	"\vseat_number\x18\x02 \x01(\x05R\n" +
	"seatNumber\x12 \n" +
	"\x04user\x18\x03 \x01(\v2\f.ticket.UserR\x04user\"2\n" +
	"\x1aRemoveUserFromTrainRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"Q\n" +
	"\x1bRemoveUserFromTrainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"h\n" +
	"\x15ModifyUserSeatRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\asection\x18\x02 \x01(\tR\asection\x12\x1f\n" +
	"\vseat_number\x18\x03 \x01(\x05R\n" +
	"seatNumber\"C\n" +
	"\x16ModifyUserSeatResponse\x12)\n" +
	"\areceipt\x18\x01 \x01(\v2\x0f.ticket.ReceiptR\areceipt\"\x90\x01\n" +
	"\aReceipt\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12 \n" +
	"\x04user\x18\x03 \x01(\v2\f.ticket.UserR\x04user\x12\x1d\n" +
	"\n" +
	"price_paid\x18\x04 \x01(\x05R\tpricePaid\x12 \n" +
	"\x04seat\x18\x05 \x01(\v2\f.ticket.SeatR\x04seat\"X\n" +
	"\x04User\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"A\n" +
	"\x04Seat\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x12\x1f\n" +
	"\vseat_number\x18\x02 \x01(\x05R\n" +
	"seatNumber2\xb9\x03\n" +
	"\rTicketService\x12O\n" +
	"\x0ePurchaseTicket\x12\x1d.ticket.PurchaseTicketRequest\x1a\x1e.ticket.PurchaseTicketResponse\x12R\n" +
	"\x0fViewUserReceipt\x12\x1e.ticket.ViewUserReceiptRequest\x1a\x1f.ticket.ViewUserReceiptResponse\x12R\n" +
	"\x0fViewAllocations\x12\x1e.ticket.ViewAllocationsRequest\x1a\x1f.ticket.ViewAllocationsResponse\x12^\n" +
	"\x13RemoveUserFromTrain\x12\".ticket.RemoveUserFromTrainRequest\x1a#.ticket.RemoveUserFromTrainResponse\x12O\n" +
	"\x0eModifyUserSeat\x12\x1d.ticket.ModifyUserSeatRequest\x1a\x1e.ticket.ModifyUserSeatResponseB6Z4github.com/cloudbees/train-ticket-service/api/ticketb\x06proto3"

var (
	file_api_ticket_proto_rawDescOnce sync.Once
	file_api_ticket_proto_rawDescData []byte
)

func file_api_ticket_proto_rawDescGZIP() []byte {
	file_api_ticket_proto_rawDescOnce.Do(func() {
		file_api_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ticket_proto_rawDesc), len(file_api_ticket_proto_rawDesc)))
	})
	return file_api_ticket_proto_rawDescData
}

var file_api_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_ticket_proto_goTypes = []any{
	(*PurchaseTicketRequest)(nil),       // 0: ticket.PurchaseTicketRequest
	(*PurchaseTicketResponse)(nil),      // 1: ticket.PurchaseTicketResponse
	(*ViewUserReceiptRequest)(nil),      // 2: ticket.ViewUserReceiptRequest
	(*ViewUserReceiptResponse)(nil),     // 3: ticket.ViewUserReceiptResponse
	(*ViewAllocationsRequest)(nil),      // 4: ticket.ViewAllocationsRequest
	(*ViewAllocationsResponse)(nil),     // 5: ticket.ViewAllocationsResponse
	(*Allocation)(nil),                  // 6: ticket.Allocation
	(*RemoveUserFromTrainRequest)(nil),  // 7: ticket.RemoveUserFromTrainRequest
	(*RemoveUserFromTrainResponse)(nil), // 8: ticket.RemoveUserFromTrainResponse
	(*ModifyUserSeatRequest)(nil),       // 9: ticket.ModifyUserSeatRequest
	(*ModifyUserSeatResponse)(nil),      // 10: ticket.ModifyUserSeatResponse
	(*Receipt)(nil),                     // 11: ticket.Receipt
	(*User)(nil),                        // 12: ticket.User
	(*Seat)(nil),                        // 13: ticket.Seat
}
var file_api_ticket_proto_depIdxs = []int32{
	11, // 0: ticket.PurchaseTicketResponse.receipt:type_name -> ticket.Receipt
	11, // 1: ticket.ViewUserReceiptResponse.receipt:type_name -> ticket.Receipt
	6,  // 2: ticket.ViewAllocationsResponse.allocations:type_name -> ticket.Allocation
	12, // 3: ticket.Allocation.user:type_name -> ticket.User
	11, // 4: ticket.ModifyUserSeatResponse.receipt:type_name -> ticket.Receipt
	12, // 5: ticket.Receipt.user:type_name -> ticket.User
	13, // 6: ticket.Receipt.seat:type_name -> ticket.Seat
	0,  // 7: ticket.TicketService.PurchaseTicket:input_type -> ticket.PurchaseTicketRequest
	2,  // 8: ticket.TicketService.ViewUserReceipt:input_type -> ticket.ViewUserReceiptRequest
	4,  // 9: ticket.TicketService.ViewAllocations:input_type -> ticket.ViewAllocationsRequest
	7,  // 10: ticket.TicketService.RemoveUserFromTrain:input_type -> ticket.RemoveUserFromTrainRequest
	9,  // 11: ticket.TicketService.ModifyUserSeat:input_type -> ticket.ModifyUserSeatRequest
	1,  // 12: ticket.TicketService.PurchaseTicket:output_type -> ticket.PurchaseTicketResponse
	3,  // 13: ticket.TicketService.ViewUserReceipt:output_type -> ticket.ViewUserReceiptResponse
	5,  // 14: ticket.TicketService.ViewAllocations:output_type -> ticket.ViewAllocationsResponse
	8,  // 15: ticket.TicketService.RemoveUserFromTrain:output_type -> ticket.RemoveUserFromTrainResponse
	10, // 16: ticket.TicketService.ModifyUserSeat:output_type -> ticket.ModifyUserSeatResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_ticket_proto_init() }
func file_api_ticket_proto_init() {
	if File_api_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ticket_proto_rawDesc), len(file_api_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ticket_proto_goTypes,
		DependencyIndexes: file_api_ticket_proto_depIdxs,
		MessageInfos:      file_api_ticket_proto_msgTypes,
	}.Build()
	File_api_ticket_proto = out.File
	file_api_ticket_proto_goTypes = nil
	file_api_ticket_proto_depIdxs = nil
}
