// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/ticket.proto

package ticket

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TicketService_PurchaseTicket_FullMethodName      = "/ticket.TicketService/PurchaseTicket"
	TicketService_ViewUserReceipt_FullMethodName     = "/ticket.TicketService/ViewUserReceipt"
	TicketService_ViewAllocations_FullMethodName     = "/ticket.TicketService/ViewAllocations"
	TicketService_RemoveUserFromTrain_FullMethodName = "/ticket.TicketService/RemoveUserFromTrain"
	TicketService_ModifyUserSeat_FullMethodName      = "/ticket.TicketService/ModifyUserSeat"
)

// TicketServiceClient is the client API for TicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TicketService provides APIs for purchasing and managing train tickets
type TicketServiceClient interface {
	// PurchaseTicket - Public API to purchase a ticket
	// Automatically assigns a seat and returns a receipt
	PurchaseTicket(ctx context.Context, in *PurchaseTicketRequest, opts ...grpc.CallOption) (*PurchaseTicketResponse, error)
	// ViewUserReceipt - Authenticated API to view user's own receipt
	// Reads user info from JWT in metadata
	ViewUserReceipt(ctx context.Context, in *ViewUserReceiptRequest, opts ...grpc.CallOption) (*ViewUserReceiptResponse, error)
	// ViewAllocations - Admin API to view all seat allocations
	// Can be filtered by section (A or B)
	ViewAllocations(ctx context.Context, in *ViewAllocationsRequest, opts ...grpc.CallOption) (*ViewAllocationsResponse, error)
	// RemoveUserFromTrain - Authenticated API to remove a user from the train
	// User can remove themselves, admin can remove any user
	RemoveUserFromTrain(ctx context.Context, in *RemoveUserFromTrainRequest, opts ...grpc.CallOption) (*RemoveUserFromTrainResponse, error)
	// ModifyUserSeat - Authenticated API to modify a user's seat assignment
	// User can modify their own seat, admin can modify any user's seat
	ModifyUserSeat(ctx context.Context, in *ModifyUserSeatRequest, opts ...grpc.CallOption) (*ModifyUserSeatResponse, error)
}

type ticketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketServiceClient(cc grpc.ClientConnInterface) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) PurchaseTicket(ctx context.Context, in *PurchaseTicketRequest, opts ...grpc.CallOption) (*PurchaseTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_PurchaseTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ViewUserReceipt(ctx context.Context, in *ViewUserReceiptRequest, opts ...grpc.CallOption) (*ViewUserReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewUserReceiptResponse)
	err := c.cc.Invoke(ctx, TicketService_ViewUserReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ViewAllocations(ctx context.Context, in *ViewAllocationsRequest, opts ...grpc.CallOption) (*ViewAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewAllocationsResponse)
	err := c.cc.Invoke(ctx, TicketService_ViewAllocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) RemoveUserFromTrain(ctx context.Context, in *RemoveUserFromTrainRequest, opts ...grpc.CallOption) (*RemoveUserFromTrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserFromTrainResponse)
	err := c.cc.Invoke(ctx, TicketService_RemoveUserFromTrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ModifyUserSeat(ctx context.Context, in *ModifyUserSeatRequest, opts ...grpc.CallOption) (*ModifyUserSeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyUserSeatResponse)
	err := c.cc.Invoke(ctx, TicketService_ModifyUserSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServiceServer is the server API for TicketService service.
// All implementations must embed UnimplementedTicketServiceServer
// for forward compatibility.
//
// TicketService provides APIs for purchasing and managing train tickets
type TicketServiceServer interface {
	// PurchaseTicket - Public API to purchase a ticket
	// Automatically assigns a seat and returns a receipt
	PurchaseTicket(context.Context, *PurchaseTicketRequest) (*PurchaseTicketResponse, error)
	// ViewUserReceipt - Authenticated API to view user's own receipt
	// Reads user info from JWT in metadata
	ViewUserReceipt(context.Context, *ViewUserReceiptRequest) (*ViewUserReceiptResponse, error)
	// ViewAllocations - Admin API to view all seat allocations
	// Can be filtered by section (A or B)
	ViewAllocations(context.Context, *ViewAllocationsRequest) (*ViewAllocationsResponse, error)
	// RemoveUserFromTrain - Authenticated API to remove a user from the train
	// User can remove themselves, admin can remove any user
	RemoveUserFromTrain(context.Context, *RemoveUserFromTrainRequest) (*RemoveUserFromTrainResponse, error)
	// ModifyUserSeat - Authenticated API to modify a user's seat assignment
	// User can modify their own seat, admin can modify any user's seat
	ModifyUserSeat(context.Context, *ModifyUserSeatRequest) (*ModifyUserSeatResponse, error)
	mustEmbedUnimplementedTicketServiceServer()
}

// UnimplementedTicketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketServiceServer struct{}

func (UnimplementedTicketServiceServer) PurchaseTicket(context.Context, *PurchaseTicketRequest) (*PurchaseTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseTicket not implemented")
}
func (UnimplementedTicketServiceServer) ViewUserReceipt(context.Context, *ViewUserReceiptRequest) (*ViewUserReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewUserReceipt not implemented")
}
func (UnimplementedTicketServiceServer) ViewAllocations(context.Context, *ViewAllocationsRequest) (*ViewAllocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewAllocations not implemented")
}
func (UnimplementedTicketServiceServer) RemoveUserFromTrain(context.Context, *RemoveUserFromTrainRequest) (*RemoveUserFromTrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserFromTrain not implemented")
}
func (UnimplementedTicketServiceServer) ModifyUserSeat(context.Context, *ModifyUserSeatRequest) (*ModifyUserSeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyUserSeat not implemented")
}
func (UnimplementedTicketServiceServer) mustEmbedUnimplementedTicketServiceServer() {}
func (UnimplementedTicketServiceServer) testEmbeddedByValue()                       {}

// UnsafeTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServiceServer will
// result in compilation errors.
type UnsafeTicketServiceServer interface {
	mustEmbedUnimplementedTicketServiceServer()
}

func RegisterTicketServiceServer(s grpc.ServiceRegistrar, srv TicketServiceServer) {
	// If the following call pancis, it indicates UnimplementedTicketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketService_ServiceDesc, srv)
}

func _TicketService_PurchaseTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).PurchaseTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_PurchaseTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).PurchaseTicket(ctx, req.(*PurchaseTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ViewUserReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewUserReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ViewUserReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ViewUserReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ViewUserReceipt(ctx, req.(*ViewUserReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ViewAllocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ViewAllocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ViewAllocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ViewAllocations(ctx, req.(*ViewAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_RemoveUserFromTrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserFromTrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).RemoveUserFromTrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_RemoveUserFromTrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).RemoveUserFromTrain(ctx, req.(*RemoveUserFromTrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ModifyUserSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyUserSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ModifyUserSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ModifyUserSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ModifyUserSeat(ctx, req.(*ModifyUserSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketService_ServiceDesc is the grpc.ServiceDesc for TicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PurchaseTicket",
			Handler:    _TicketService_PurchaseTicket_Handler,
		},
		{
			MethodName: "ViewUserReceipt",
			Handler:    _TicketService_ViewUserReceipt_Handler,
		},
		{
			MethodName: "ViewAllocations",
			Handler:    _TicketService_ViewAllocations_Handler,
		},
		{
			MethodName: "RemoveUserFromTrain",
			Handler:    _TicketService_RemoveUserFromTrain_Handler,
		},
		{
			MethodName: "ModifyUserSeat",
			Handler:    _TicketService_ModifyUserSeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ticket.proto",
}
